
# ------------------------------------------------------------------------------
# Acceso a la API
# ------------------------------------------------------------------------------
api:
  url: 'https://api.crc-sas.org/ws-api'
  user: 'clima' 
  pass: 'Dcft^&*('
# ------------------------------------------------------------------------------
