
# ------------------------------------------------------------------------------
# Directorios de trabajo
# ------------------------------------------------------------------------------
dir:  
  lib: ./lib/
  inputs: inputs/
  outputs: ./outputs/
  shared: ./shared/
  weather: weather/
  run: run/
  logs: log/
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Soils files 
# ------------------------------------------------------------------------------
soil_file: "SOIL.SOL"
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# DSSAT 
# ------------------------------------------------------------------------------
dssat: 
  models:
    SB: 'SBGRO047'
    WH: 'WHCER047'
    MZ: 'MZCER047'
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Cantidad maxima de procesos paralelos
# ------------------------------------------------------------------------------
max.procesos: 8
# ------------------------------------------------------------------------------
